// Cloudflare R2 upload via presigned URL approach
// We use fetch directly against the R2 S3-compatible API

const R2_PUBLIC_URL = import.meta.env.VITE_R2_PUBLIC_URL

/**
 * Upload a file to R2 via a presigned URL generated by our Supabase Edge Function.
 * @param {File} file
 * @param {string} userId
 * @param {(pct: number) => void} onProgress
 * @returns {Promise<string>} public URL of the uploaded file
 */
export async function uploadToR2(file, userId, onProgress) {
  const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_')
  const key = `${userId}/${Date.now()}-${safeName}`

  // Normalize content type — browsers sometimes leave EPUB type empty
  const contentType = file.type || (file.name.endsWith('.epub') ? 'application/epub+zip' : 'application/octet-stream')

  // Get a presigned PUT URL from our edge function
  const fnUrl = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/get-upload-url`
  const fnRes = await fetch(fnUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'apikey': import.meta.env.VITE_SUPABASE_ANON_KEY,
      'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}`,
    },
    body: JSON.stringify({ key, contentType })
  })

  if (!fnRes.ok) {
    const text = await fnRes.text()
    throw new Error(`Edge function error ${fnRes.status}: ${text}`)
  }

  const { presignedUrl } = await fnRes.json()

  // Upload directly to R2
  await new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest()
    xhr.open('PUT', presignedUrl)
    xhr.upload.onprogress = (e) => {
      if (e.lengthComputable && onProgress) {
        onProgress(Math.round((e.loaded / e.total) * 100))
      }
    }
    xhr.onload = () => xhr.status === 200 ? resolve() : reject(new Error(`Upload failed: ${xhr.status}`))
    xhr.onerror = () => reject(new Error('Upload network error'))
    xhr.send(file)
  })

  return `${R2_PUBLIC_URL}/${key}`
}

/**
 * Delete a file from R2 via our edge function.
 */
export async function deleteFromR2(key) {
  const { error } = await import('./supabase.js')
    .then(({ supabase }) =>
      supabase.functions.invoke('delete-file', { body: { key } })
    )
  if (error) throw new Error('Failed to delete file: ' + error.message)
}
